import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UiProvider } from './components/provider/UiProvider';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '語彙力学習サイト',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        <Suspense>
          <UiProvider>{children}</UiProvider>
        </Suspense>
      </body>
    </html>
  );
}
